#database_setup.yml
- name: Database Setup play
  hosts: database_servers
  become: true
  vars:
    min_ram_size_bytes: 1000000
    supported_distros:
    - Ubuntu
  tasks:
    - name: Setup Database tasks on supported hosts w/ Min. RAM
      include_tasks: "{{ ansible_distribution }}_database_tasks.yml"
      when:
        - ansible_distribution in supported_distros
        - ansible_memtotal_mb*1024*1024 >= min_ram_size_bytes 
    - name: Print a message for unsupported Distros
      debug:
        msg: >
          {{ inventory_hostname }} is a
          {{ ansible_distribution }}-based host, which is not one
          of the supported distributions ({{ supported_distros }})
      when: ansible_distribution not in supported_distros
    - name: Print a message for systems with insufficient RAM
      debug:
        msg: >
          {{ inventory_hostname }} does not meet the minimum
          RAM requirements of {{ min_ram_size_bytes }} bytes.
      when: ansible_memtotal_mb*1024*1024 < min_ram_size_bytes

#database_user_tasks.yml
- name: Ensure database permission groups exist
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ host_permission_groups }}"

- name: Ensure Database Users exist 
  user: 
    name: "{{ item.username }}" 
    groups: "{{ item.role }}" 
    append: yes 
    state: present 
  loop: "{{ user_list }}" 
  when: item.role in host_permission_groups

- name: MySQL user
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    priv: '*.*:{{ item.access}}'
    state: present
  loop: "{{ user_list }}"
  when: "item.role in host_permission_groups"
