# Task to install apache2 package
- name: Install apache2 package
  apt:
    name: apache2
    state: present
    update_cache: yes

# Task to ensure apache2 service is started and enabled
- name: Ensure apache2 service is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

# Task to use template module to install quiz-roles.conf.j2
- name: Install quiz-roles.conf template
  template:
    src: quiz-roles.conf.j2
    dest: /etc/apache2/sites-available/quiz-roles.conf
  notify:
    - Restart apache2 service

# Task to enable the webserver configuration using a2ensite command
- name: Enable quiz-roles webserver configuration
  command: a2ensite quiz-roles.conf
  notify:
    - Restart apache2 service

# Task to copy files using the copy module
- name: Copy html-quiz/ to /var/www/quiz-roles/{{ ansible_hostname }}
  copy:
    src: html-quiz/
    dest: /var/www/quiz-roles/{{ ansible_hostname }}
    owner: www-data
    group: www-data
    mode: '0755'
