# Task to install apache2 package
- name: Install Apache2 package
  apt:
    name: apache2
    state: present
  become: yes

# Task to ensure Apache2 service is started and enabled
- name: Ensure Apache2 service is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes

# Task to deploy webserver configuration using template module
- name: Deploy quiz-roles Apache2 configuration
  template:
    src: quiz-roles.conf.j2
    dest: /etc/apache2/sites-available/quiz-roles.conf
  notify:
    - Restart Apache2
  become: yes

# Disable default site configuration
- name: Disable default configuration
  command: a2dissite 000-default.conf
  become: yes

# Task to enable the quiz-roles site configuration using a2ensite
- name: Enable quiz-roles site
  command: a2ensite quiz-roles.conf
  notify:
    - Restart Apache2
  become: yes

# Task to copy HTML files to the managed host's web directory
- name: Copy HTML files to web directory
  copy:
    src: html-quiz/
    dest: /var/www/quiz-roles/{{ ansible_hostname }}
    owner: www-data
    group: www-data
    mode: '0755'
  become: yes
