- hosts: managed
  become: yes
  tasks:
    - name: Include encrypted variables
      ansible.builtin.include_vars:
        file: quiz-Secret.yml
        name: secrets
        ansible_vault_password_file: ./quiz-pass

    - name: Create a user with the encrypted password
      ansible.builtin.user:
        name: "{{ secrets.username }}"
        password: "{{ secrets.passwd }}"