- hosts: managed
  become: yes
  vars_files:
    - quiz-Secret.yml
  tasks:
    - name: Create users from quiz-Secret.yml
      user:
        name: "{{username}}"
        password: "{{pw | password_hash('sha512')}}"